// All Qur'an data access. Local-first (public/data/, generated by
// scripts/build-quran-data.mjs); falls back to quran.com (glyphs) and
// alquran.cloud (translations) when the bundle is missing a page.

const BASE = 'https://api.alquran.cloud/v1'

// Edition identifiers used by the app.
const ARABIC = 'ar.alafasy' // default Arabic text + audio edition
const TRANSLATION = 'en.asad'
const TRANSLITERATION = 'en.transliteration'

// Selectable translations (alquran.cloud text editions).
export const TRANSLATIONS = [
  { id: 'en.asad', name: 'English — Muhammad Asad' },
  { id: 'en.sahih', name: 'English — Saheeh International' },
  { id: 'ms.basmeih', name: 'Malay — Abdullah Basmeih' },
  { id: 'id.indonesian', name: 'Indonesian — Kementerian Agama RI' },
]

// Selectable reciters. Each is an alquran.cloud verse-by-verse audio edition
// that also carries the Uthmani Arabic text, so one request gives both.
export const RECITERS = [
  { id: 'ar.alafasy', name: 'Mishary Rashid Alafasy' },
  { id: 'ar.abdulbasitmurattal', name: 'Abdul Basit (Murattal)' },
  { id: 'ar.husary', name: 'Mahmoud Khalil Al-Husary' },
  { id: 'ar.minshawi', name: 'Mohamed El-Minshawi' },
  { id: 'ar.abdurrahmaansudais', name: 'Abdurrahman As-Sudais' },
  { id: 'ar.shaatree', name: 'Abu Bakr Ash-Shaatree' },
  { id: 'ar.muhammadayyoub', name: 'Muhammad Ayyoub' },
  { id: 'ar.mahermuaiqly', name: 'Maher Al Muaiqly' },
  { id: 'ar.hudhaify', name: 'Ali Al-Hudhaify' },
  { id: 'ar.ahmedajamy', name: 'Ahmed Al-Ajamy' },
  { id: 'ar.hanirifai', name: 'Hani Ar-Rifai' },
]

export const TOTAL_PAGES = 604
export const TOTAL_SURAHS = 114

// --- bundled local data (public/data/) -------------------------------------
// When the data files are present (generated by scripts/build-quran-data.mjs),
// the app serves its own content — no third-party API at runtime. Each loader
// returns null if the file is absent, so callers fall back to the live APIs
// and keep working before/without the bundle.
const DATA_BASE = (import.meta.env.BASE_URL || '/') + 'data/'
let metaCache
const transCache = {}
const pageCache = {}

async function loadJson(path) {
  try {
    const res = await fetch(DATA_BASE + path)
    return res.ok ? await res.json() : null
  } catch {
    return null
  }
}
async function loadMeta() {
  if (metaCache === undefined) metaCache = await loadJson('meta.json')
  return metaCache
}
async function loadLocalPage(page) {
  if (!(page in pageCache)) pageCache[page] = await loadJson(`page/${page}.json`)
  return pageCache[page]
}
async function loadTranslation(edition) {
  if (!(edition in transCache)) {
    transCache[edition] = await loadJson(`translation/${edition}.json`)
  }
  return transCache[edition]
}

// Per-ayah recitation streams from the islamic.network CDN by global ayah
// number (1–6236) — the same files alquran.cloud points to, just computed.
function audioUrl(edition, globalNumber) {
  return `https://cdn.islamic.network/quran/audio/128/${edition}/${globalNumber}.mp3`
}

function surahsFromVerses(verses, meta) {
  const ids = [...new Set(verses.map((v) => v.surah))].sort((a, b) => a - b)
  return ids.map((id) => ({
    number: id,
    englishName: meta?.[id]?.en || SURAH_NAMES[id - 1] || `Surah ${id}`,
  }))
}

function cacheKey(page, editions) {
  return `hifz:page:${page}:${editions.join(',')}`
}

// Per-ayah QCF v2 glyph words from quran.com, keyed by "surah:ayah". Each ayah
// gets { words: [{ code, page, end }], text } where `code` is the QCF glyph
// (rendered in the matching per-page font for an exact mushaf look) and `text`
// is the reconstructed Uthmani string used as a fallback. Returns null on
// failure (the reader then falls back to the alquran.cloud Arabic text).
async function fetchPageWords(page) {
  try {
    const url =
      `${QURAN_API}/verses/by_page/${page}` +
      `?words=true&per_page=300` +
      `&word_fields=code_v2,text_uthmani,page_number,char_type_name`
    const res = await fetch(url)
    if (!res.ok) return null
    const json = await res.json()
    const verses = json?.verses
    if (!Array.isArray(verses)) return null
    const byVerse = {}
    for (const v of verses) {
      const words = []
      let text = ''
      for (const w of v.words || []) {
        const end = w.char_type_name === 'end'
        if (w.code_v2) words.push({ code: w.code_v2, page: w.page_number || page, end })
        if (!end && w.text_uthmani) text += (text ? ' ' : '') + w.text_uthmani
      }
      if (words.length) byVerse[v.verse_key] = { words, text }
    }
    return byVerse
  } catch {
    return null
  }
}

// Fetch a single mushaf page, optionally with translation/transliteration.
// Returns { page, surahs, ayahs } where each ayah is fully normalised.
export async function getPage(page, opts = {}) {
  // The chosen reciter edition supplies both the Arabic text and the audio.
  const arabicEdition =
    opts.reciter && RECITERS.some((r) => r.id === opts.reciter)
      ? opts.reciter
      : ARABIC
  const editions = [arabicEdition]
  const translationEdition =
    opts.translationEdition &&
    TRANSLATIONS.some((t) => t.id === opts.translationEdition)
      ? opts.translationEdition
      : TRANSLATION
  if (opts.translation) editions.push(translationEdition)
  if (opts.transliteration) editions.push(TRANSLITERATION)

  // Local-first: assemble from the bundled data when present.
  const localPage = await loadLocalPage(page)
  if (localPage?.verses?.length) {
    const [meta, trans, translit] = await Promise.all([
      loadMeta(),
      opts.translation ? loadTranslation(translationEdition) : null,
      opts.transliteration ? loadTranslation(TRANSLITERATION) : null,
    ])
    const ayahs = localPage.verses.map((v) => ({
      number: v.num,
      numberInSurah: v.ayah,
      surahNumber: v.surah,
      surahName: meta?.[v.surah]?.ar,
      surahEnglishName: meta?.[v.surah]?.en || SURAH_NAMES[v.surah - 1],
      arabic: v.text,
      words: v.words,
      showBasmalah: v.ayah === 1 && v.surah !== 1 && v.surah !== 9,
      audio: audioUrl(arabicEdition, v.num),
      translation: trans ? trans[v.key] || null : null,
      transliteration: translit ? translit[v.key] || null : null,
    }))
    return { page, surahs: surahsFromVerses(localPage.verses, meta), ayahs }
  }

  // Remote fallback (live APIs) — used before/without the bundled data.
  const key = cacheKey(page, editions)
  const cached = sessionStorage.getItem(key)
  if (cached) {
    try {
      return JSON.parse(cached)
    } catch {
      /* fall through to refetch */
    }
  }

  // The page endpoint serves a single edition per request (unlike surah/ayah,
  // it has no /editions/ multiplexing), so fetch each edition in parallel and
  // zip the ayahs together by index. In parallel, fetch the official QCF v2
  // glyph words from quran.com for an exact mushaf rendering of each ayah.
  const [editionsData, wordsByVerse] = await Promise.all([
    Promise.all(
      editions.map(async (edition) => {
        const url = `${BASE}/page/${page}/${edition}`
        const res = await fetch(url)
        if (!res.ok) throw new Error(`Request failed (${res.status})`)

        const json = await res.json()
        if (json.code !== 200 || !json.data || !Array.isArray(json.data.ayahs)) {
          throw new Error('Unexpected response from the Quran service.')
        }
        return json.data
      })
    ),
    fetchPageWords(page),
  ])

  const result = normalise(editionsData, page, arabicEdition, translationEdition, wordsByVerse)
  try {
    sessionStorage.setItem(key, JSON.stringify(result))
  } catch {
    /* sessionStorage full — non-fatal */
  }
  return result
}

// The Arabic editions prepend the basmalah to the first ayah of every surah
// except Al-Faatiha (where it is ayah 1) and At-Tawba (which has none). Split
// it off so callers can show it as its own centered line above "الٓمٓ" etc.
// The basmalah is exactly four words; only a leading basmalah produces a first
// word whose letters are بسم, so this is safe to detect and strip.
function splitBasmalah(text, surahNumber, numberInSurah) {
  if (numberInSurah !== 1 || surahNumber === 1 || surahNumber === 9) {
    return { text, showBasmalah: false }
  }
  const words = text.trim().split(/\s+/)
  const firstWordLetters = words[0]?.replace(/[^ء-ي]/g, '')
  if (words.length > 4 && firstWordLetters === 'بسم') {
    return { text: words.slice(4).join(' '), showBasmalah: true }
  }
  return { text, showBasmalah: false }
}

// Each per-edition page response carries the same ayahs in the same order.
// Zip them together by index.
function normalise(
  editionsData,
  page,
  arabicEdition = ARABIC,
  translationEdition = TRANSLATION,
  wordsByVerse = null
) {
  const byIdentifier = {}
  editionsData.forEach((ed) => {
    byIdentifier[ed.edition.identifier] = ed.ayahs
  })

  const arabicAyahs = byIdentifier[arabicEdition] || []
  const translationAyahs = byIdentifier[translationEdition] || []
  const transliterationAyahs = byIdentifier[TRANSLITERATION] || []

  const ayahs = arabicAyahs.map((a, i) => {
    const surahNumber = a.surah?.number
    const showBasmalah =
      a.numberInSurah === 1 && surahNumber !== 1 && surahNumber !== 9
    // Prefer the official QCF v2 glyphs (exact mushaf rendering). `words` is
    // used when its page fonts are loaded; `arabic` (the reconstructed Uthmani
    // string, or the alquran.cloud text) is the fallback shown otherwise.
    const vw = wordsByVerse?.[`${surahNumber}:${a.numberInSurah}`]
    const words = vw?.words || null
    const arabic = vw?.text || splitBasmalah(a.text, surahNumber, a.numberInSurah).text
    return {
      words,
      number: a.number,
      numberInSurah: a.numberInSurah,
      surahNumber,
      surahName: a.surah?.name,
      surahEnglishName: a.surah?.englishName,
      arabic,
      showBasmalah,
      audio: a.audio || a.audioSecondary?.[0] || null,
      translation: translationAyahs[i]?.text || null,
      transliteration: transliterationAyahs[i]?.text || null,
    }
  })

  // Distinct surahs appearing on this page, for section headers.
  const surahs = []
  ayahs.forEach((a) => {
    if (!surahs.some((s) => s.number === a.surahNumber)) {
      surahs.push({
        number: a.surahNumber,
        name: a.surahName,
        englishName: a.surahEnglishName,
      })
    }
  })

  return { page, surahs, ayahs }
}

// Fetch every ayah of a surah, assembled from the mushaf pages it spans.
// Returns { number, name, englishName, ayahCount, ayahs }. Ayahs carry the
// same shape as getPage()'s (words/arabic/translation/audio/etc).
export async function getSurah(surahNumber, opts = {}) {
  const meta = await loadMeta()
  const ayahCount = SURAH_AYAHS[surahNumber - 1]
  const ayahs = []
  let page = SURAH_PAGES[surahNumber - 1]
  while (page <= TOTAL_PAGES && ayahs.length < ayahCount) {
    const pageData = await getPage(page, opts)
    for (const a of pageData.ayahs) {
      if (a.surahNumber === surahNumber) ayahs.push(a)
    }
    page++
  }
  return {
    number: surahNumber,
    name: meta?.[surahNumber]?.ar,
    englishName: meta?.[surahNumber]?.en || SURAH_NAMES[surahNumber - 1],
    ayahCount,
    ayahs: ayahs.slice(0, ayahCount),
  }
}

// Every surah's basic info (number, Arabic/English name, ayah count) — the
// data behind the surah index. Cheap: only meta.json is fetched.
export async function listSurahs() {
  const meta = await loadMeta()
  return Array.from({ length: TOTAL_SURAHS }, (_, i) => {
    const number = i + 1
    return {
      number,
      name: meta?.[number]?.ar || '',
      englishName: meta?.[number]?.en || SURAH_NAMES[i],
      ayahCount: SURAH_AYAHS[i],
    }
  })
}

// --- exact Madani mushaf (QCF v2 page glyphs) ------------------------------
// quran.com's word-by-word data carries per-word PUA glyph codes (`code_v2`)
// that render as the printed Madani mushaf when shown in the matching per-page
// font. We group words into the page's 15 lines for a faithful layout.

const QURAN_API = 'https://api.quran.com/api/v4'

// Per-page QCF v2 font file. Centralised so it's a one-line change if the CDN
// path differs. The @font-face family is assigned by fonts.js as `qcf2p<n>`.
export function mushafFontUrl(page) {
  // jsDelivr mirror of the verified QCF v2 page fonts, pinned to a branch so
  // the path resolves reliably. Lazy-loaded one page at a time.
  return `https://cdn.jsdelivr.net/gh/quran/quran.com-frontend-next@master/public/fonts/quran/hafs/v2/woff2/p${page}.woff2`
}

export async function getMushafPage(page) {
  // Local-first: use the bundled page glyphs when present.
  const localPage = await loadLocalPage(page)
  if (localPage?.lines?.length) {
    const meta = await loadMeta()
    return {
      page,
      lines: localPage.lines,
      surahs: surahsFromVerses(localPage.verses, meta),
    }
  }

  const key = `hifz:mushaf:${page}`
  const cached = sessionStorage.getItem(key)
  if (cached) {
    try {
      return JSON.parse(cached)
    } catch {
      /* refetch */
    }
  }

  const url =
    `${QURAN_API}/verses/by_page/${page}` +
    `?words=true&per_page=300&fields=chapter_id` +
    `&word_fields=code_v2,line_number,page_number,char_type_name`
  const res = await fetch(url)
  if (!res.ok) throw new Error(`Request failed (${res.status})`)
  const json = await res.json()
  const verses = json?.verses
  if (!Array.isArray(verses) || verses.length === 0) {
    throw new Error('Unexpected response from the Quran service.')
  }

  // Flatten words, then group by their line number (1..15) preserving order.
  const lineMap = new Map()
  const chapterIds = new Set()
  for (const v of verses) {
    if (v.chapter_id) chapterIds.add(v.chapter_id)
    for (const w of v.words || []) {
      const ln = w.line_number || 0
      if (!lineMap.has(ln)) lineMap.set(ln, [])
      lineMap.get(ln).push({
        code: w.code_v2 || w.text || '',
        end: w.char_type_name === 'end',
      })
    }
  }
  const lines = [...lineMap.keys()]
    .sort((a, b) => a - b)
    .map((ln) => ({ lineNumber: ln, words: lineMap.get(ln) }))

  const surahs = [...chapterIds].sort((a, b) => a - b).map((id) => ({
    number: id,
    englishName: SURAH_NAMES[id - 1] || `Surah ${id}`,
  }))

  const result = { page, lines, surahs }
  try {
    sessionStorage.setItem(key, JSON.stringify(result))
  } catch {
    /* non-fatal */
  }
  return result
}

// Resolve the mushaf page that a given surah:ayah falls on.
export async function getAyahPage(surah, ayah) {
  const ref = `${surah}:${ayah}`

  // Local-first: the bundled ayah→page index.
  const idx = await loadJson('ayah-pages.json')
  if (idx && idx[ref]) return idx[ref]

  const key = `hifz:ayahpage:${ref}`
  const cached = sessionStorage.getItem(key)
  if (cached) return Number(cached)

  const res = await fetch(`${BASE}/ayah/${ref}`)
  if (!res.ok) throw new Error(`Request failed (${res.status})`)
  const json = await res.json()
  const page = json?.data?.page
  if (!page) throw new Error('Could not resolve that ayah.')
  try {
    sessionStorage.setItem(key, String(page))
  } catch {
    /* non-fatal */
  }
  return page
}

// Mushaf page where each Juz begins, indexed 0 → Juz 1 (Madani 604-page).
export const JUZ_START_PAGES = [
  1, 22, 42, 62, 82, 102, 121, 142, 162, 182, 201, 222, 242, 262, 282, 302,
  322, 342, 362, 382, 402, 422, 442, 462, 482, 502, 522, 542, 562, 582,
]

// Which Juz (1–30) a given mushaf page falls in.
export function juzForPage(page) {
  let juz = 1
  for (let i = 0; i < JUZ_START_PAGES.length; i++) {
    if (page >= JUZ_START_PAGES[i]) juz = i + 1
    else break
  }
  return juz
}

// Mushaf page where each surah begins, indexed 0 → Surah 1 (Madani 604-page).
export const SURAH_PAGES = [
  1, 2, 50, 77, 106, 128, 151, 177, 187, 208, 221, 235, 249, 255, 262, 267,
  282, 293, 305, 312, 322, 332, 342, 350, 359, 367, 377, 385, 396, 404, 411,
  415, 418, 428, 434, 440, 446, 453, 458, 467, 477, 483, 489, 496, 499, 502,
  507, 511, 515, 518, 520, 523, 526, 528, 531, 534, 537, 542, 545, 549, 551,
  553, 554, 556, 558, 560, 562, 564, 566, 568, 570, 572, 574, 575, 577, 578,
  580, 582, 583, 585, 586, 587, 587, 589, 590, 591, 591, 592, 593, 594, 595,
  595, 596, 596, 597, 597, 598, 598, 599, 599, 600, 600, 601, 601, 601, 602,
  602, 602, 603, 603, 603, 604, 604, 604,
]

// Ayah count per surah (Hafs), indexed 0 → Surah 1.
export const SURAH_AYAHS = [
  7, 286, 200, 176, 120, 165, 206, 75, 129, 109, 123, 111, 43, 52, 99, 128,
  111, 110, 98, 135, 112, 78, 118, 64, 77, 227, 93, 88, 69, 60, 34, 30, 73, 54,
  45, 83, 182, 88, 75, 85, 54, 53, 89, 59, 37, 35, 38, 29, 18, 45, 60, 49, 62,
  55, 78, 96, 29, 22, 24, 13, 14, 11, 11, 18, 12, 12, 30, 52, 52, 44, 28, 28,
  20, 56, 40, 31, 50, 40, 46, 42, 29, 19, 36, 25, 22, 17, 19, 26, 30, 20, 15,
  21, 11, 8, 8, 19, 5, 8, 8, 11, 11, 8, 3, 9, 5, 4, 7, 3, 6, 3, 5, 4, 5, 6,
]

// English (transliterated) surah names, indexed 0 → Surah 1.
export const SURAH_NAMES = [
  'Al-Faatiha', 'Al-Baqara', 'Aal-i-Imraan', 'An-Nisaa', 'Al-Maaida',
  "Al-An'aam", "Al-A'raaf", 'Al-Anfaal', 'At-Tawba', 'Yunus', 'Hud', 'Yusuf',
  "Ar-Ra'd", 'Ibrahim', 'Al-Hijr', 'An-Nahl', 'Al-Israa', 'Al-Kahf', 'Maryam',
  'Taa-Haa', 'Al-Anbiyaa', 'Al-Hajj', "Al-Mu'minoon", 'An-Noor', 'Al-Furqaan',
  "Ash-Shu'araa", 'An-Naml', 'Al-Qasas', 'Al-Ankaboot', 'Ar-Room', 'Luqman',
  'As-Sajda', 'Al-Ahzaab', 'Saba', 'Faatir', 'Yaseen', 'As-Saaffaat', 'Saad',
  'Az-Zumar', 'Ghafir', 'Fussilat', 'Ash-Shura', 'Az-Zukhruf', 'Ad-Dukhaan',
  'Al-Jaathiya', 'Al-Ahqaf', 'Muhammad', 'Al-Fath', 'Al-Hujuraat', 'Qaaf',
  'Adh-Dhaariyat', 'At-Toor', 'An-Najm', 'Al-Qamar', 'Ar-Rahmaan',
  'Al-Waaqia', 'Al-Hadid', 'Al-Mujaadila', 'Al-Hashr', 'Al-Mumtahana',
  'As-Saff', "Al-Jumu'a", 'Al-Munaafiqoon', 'At-Taghaabun', 'At-Talaaq',
  'At-Tahrim', 'Al-Mulk', 'Al-Qalam', 'Al-Haaqqa', "Al-Ma'aarij", 'Nooh',
  'Al-Jinn', 'Al-Muzzammil', 'Al-Muddaththir', 'Al-Qiyaama', 'Al-Insaan',
  'Al-Mursalaat', 'An-Naba', "An-Naazi'aat", 'Abasa', 'At-Takwir',
  'Al-Infitaar', 'Al-Mutaffifin', 'Al-Inshiqaaq', 'Al-Burooj', 'At-Taariq',
  "Al-A'laa", 'Al-Ghaashiya', 'Al-Fajr', 'Al-Balad', 'Ash-Shams', 'Al-Lail',
  'Ad-Dhuhaa', 'Ash-Sharh', 'At-Tin', 'Al-Alaq', 'Al-Qadr', 'Al-Bayyina',
  'Az-Zalzala', 'Al-Aadiyaat', 'Al-Qaari’a', 'At-Takaathur', "Al-'Asr",
  'Al-Humaza', 'Al-Fil', 'Quraish', "Al-Maa'un", 'Al-Kawthar', 'Al-Kaafiroon',
  'An-Nasr', 'Al-Masad', 'Al-Ikhlaas', 'Al-Falaq', 'An-Naas',
]
