name = "hifz-sync"
main = "src/index.js"
compatibility_date = "2024-09-23"

# Public, non-secret config.
[vars]
GOOGLE_CLIENT_ID = "515296416644-ema4raa8d8t1p1sk14ijai9gk5qqstc1.apps.googleusercontent.com"

# KV namespace for synced snapshots.
[[kv_namespaces]]
binding = "HIFZ_KV"
id = "5a27590b8df848ab81308a8f43e0fbc1"
